name: CI/CD

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "build mini-hub"
          docker build --no-cache --build-arg NEXT_PUBLIC_STOREFRONT_URL=${{secrets.NEXT_PUBLIC_STOREFRONT_URL}}   --build-arg  NEXT_PUBLIC_SALEOR_API_URL=${{secrets.NEXT_PUBLIC_SALEOR_API_URL}} -f Dockerfile -t saleor/storefront:latest .

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REGISTRY }}

      - name: Push to ECR
        run: |
          echo "push image to ecr"
          docker tag saleor/storefront:latest ${{ secrets.DOCKER_REGISTRY }}/saleor/storefront:latest 
          docker push ${{ secrets.DOCKER_REGISTRY }}/saleor/storefront:latest

      - name: Deploy to ECS
        run: |
          echo "deploy"
          aws ecs update-service --region ${{ secrets.AWS_DEFAULT_REGION }} --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }}  --task-definition ${{ secrets.ECS_TASK_DEFINITION }} --force-new-deployment
